Add BaseController#lockConsumingMessageEvent
akashic-games/coe pull request #25
Opened 2020-10-29 06:32 UTC by yu-ogi

## このPullRequestが解決する内容
**一部不要な差分が含まれていたため #24 をベースにしています**

* `BaseController#lockConsumingMessageEvent: boolean` を導入します。このフラグが真の場合、 `g.MessageEvent` の消化を次フレームに遅延して処理するようにします。
  * また、セッションパラメータと同期的に `g.MessageEvent` が送信されるケースにおいて後続の `g.MessageEvent` を次フレームのイベントフィルタで処理するように修正します。
* [lerna の --hoist](https://github.com/lerna/lerna/blob/master/doc/hoist.md) を有効にするため、依存モジュールのバージョンを揃えます。
* deprecated のトリガー (`g.Scene#message` -> `onMessage` など) を修正します。

2020-10-29 06:37 UTC, yu-ogi commented on packages/coe/src/impl/COEController.ts
> +				});
こちらが本題になります。セッションパラメータ受信時に `lockConsumingMessageEvent` を次フレーム (次回の `BaseController#update`) まで真にします。

2020-10-29 06:38 UTC, yu-ogi commented on packages/coe/src/impl/Scene.ts
> +				}
`BaseController#lockConsumingMessageEvent` が真であれば対象のイベントを次フレームに処理するようにします。

2020-10-29 08:45 UTC, xnv requested changes

2020-10-29 08:45 UTC, xnv commented on packages/coe/src/impl/Scene.ts
> +				}
このフラグが立っていても、 `MessageEvent` 以外のイベント (や `playerId` がない `MessageEvent`) はそのまま素通しする挙動のようですが、これは……どういった目的によるものでしょうか。

感覚的には、このように `MessageEvent` が特別扱いされることに抵抗があります。coe 専用の特別なイベントとして予約されているものでならこういう判断もあるかもしれないんですが、 `MessageEvent` はコンテンツが生成してくることもあるイベントなので。例えばコンテンツが自分で `raiseEvent()` した `MessageEvent` と `PointDownEvent` が、片方だけロックされて後回しになるパスが存在しうるのは、かなり直観に反すると思います。(コンテンツのデバッグ中にこのようなパスの可能性を考慮に入れなければならないのは、まあ、端的に言って理不尽でしょう)

よほど限定的な条件でならともかく、一般論として「受信したイベントの順序を崩す」ことには慎重になりたいです。コンテンツが意図してやるならそれはコンテンツの自由ですが、ライブラリが暗黙にやることを期待される挙動とは考えにくいです。

2020-10-29 08:45 UTC, xnv commented on packages/coe/src/impl/BaseController.ts
> +	lockConsumingMessageEvent: boolean = false;
- JSDoc コメントがついていますが、これはコンテンツ開発者に公開される機能なのでしょうか。
  - もし非公開 (コンテンツ開発者の利用を想定しない) なら、そのことが (コメントなどで) 分かるように明示したいです。
  - もし公開するなら、この値はロックカウント (数値) である方が良さそうです。最悪複数箇所からフラグを上げ下げされた時、 boolean ではデバッグが割とつらいシーケンス系のトラブルにつながるように思えるからです。そして直接操作するよりは lock〜(), unlock〜() のメソッドを用意したいです。
- 別件で、動詞始まりだとまるでメソッドに見える点ひっかりました。

2020-10-30 00:26 UTC, yu-ogi commented on packages/coe/src/impl/Scene.ts
> +				}
> このフラグが立っていても、 MessageEvent 以外のイベント (や playerId がない MessageEvent) はそのまま素通しする挙動のようですが、これは……どういった目的によるものでしょうか。

「coe が関心を持っているのは MessageEvent のみのため」というのがおそらく適切な回答になるかと思います。
「playerId がない MessageEvent」や「Point...系イベント」は関心が無い (捕捉する必要がない) ため、素通ししていました。

> coe 専用の特別なイベントとして予約されているものでならこういう判断もあるかもしれないんですが、 MessageEvent はコンテンツが生成してくることもあるイベントなので

coe はイベント生成元についても関心が無いつもりでした。対象のイベントが第三者のシステムなのかコンテンツ自身なのかを意識せず、常に「playerId の存在する MessageEvent」のみを処理の対象としています。
そのあたりは coe のコメントにも「握りつぶされる」という抽象的な書き方ではありますが明記しております。
https://github.com/akashic-games/coe/blob/746f76f4a6f423142ac3508bf27d7a2ed11391e2/packages/coe/src/impl/Scene.ts#L11-L14

したがって、

> 例えばコンテンツが自分で raiseEvent() した MessageEvent と PointDownEvent が、片方だけロックされて後回しになるパスが存在しうる

というのは妥当なように思えます。

今回の修正では「セッションパラメータと同期的に g.MessageEvent が送信されるケースにおいて後続の g.MessageEvent を次フレームのイベントフィルタで処理する」というごくまれなケースを「例外的に」ケアすることを目的としているため、

> よほど限定的な条件でならともかく、一般論として「受信したイベントの順序を崩す」ことには慎重になりたいです。

の「よほど限定的な条件」に内包されるものなのかと認識しています。

そういう意味では https://github.com/akashic-games/coe/pull/25#discussion_r514081132 にもあるように「コンテンツ制作者からは基本的には使われない」ということを `lockConsumingMessageEvent` (名前は変更予定ですが) 側にコメントしておくべきですね。

2020-10-30 00:29 UTC, yu-ogi commented on packages/coe/src/impl/BaseController.ts
> +	lockConsumingMessageEvent: boolean = false;
>もし非公開 (コンテンツ開発者の利用を想定しない) なら、そのことが (コメントなどで) 分かるように明示したいです。

利用部分が局所的かつ影響が大きいため非公開にした方が良さそうですね。こちら対応します。

> 別件で、動詞始まりだとまるでメソッドに見える点ひっかりました。

おっしゃるとおりですね。修正します。

2020-11-04 02:57 UTC, xnv commented on packages/coe/src/impl/Scene.ts
> +				}
> 「coe が関心を持っているのは MessageEvent のみのため」というのがおそらく適切な回答になるかと思います。「playerId がない MessageEvent」や「Point...系イベント」は関心が無い

> 対象のイベントが第三者のシステムなのかコンテンツ自身なのかを意識せず、常に「playerId の存在する MessageEvent」のみを処理の対象としています。

まさに「関心がない」「処理の対象ではない」からこそ、 不要な影響を与えるべきではない、という議論をしているつもりです。

重要なのは「素通しすること」それ自体ではなく、「できるだけ透明であること」(余計な影響をライブラリユーザに与えないこと) ではないでしょうか。「素通し」はその手段の一つに過ぎないはずです。そしてここにおいて、「素通し」はもはや透明であるために最適な手段ではなくなっていると思います。

> そのあたりは coe のコメントにも「握りつぶされる」という抽象的な書き方ではありますが明記しております。

……まずそのコメントについて再考したいですね。

もし本当に「握りつぶされる」ならば、すなわち「`MessageEvent` の受信はゲーム開発者に対して完全に隠蔽される」ならば、確かに順序は問題ではないと思います。順序がどうなろうがゲーム開発者はそれに気づくことすらないからです。しかし本当でしょうか。現実には「そのまま tick には載せない代わりに、ゲーム開発者に通知するので、必要なら "ゲーム開発者が改めて送出せよ"」という形ではないでしょうか。握りつぶす＝隠蔽するどころか、ゲーム開発者にはむしろ積極的に露出されています。

"エンジンから見れば" 握りつぶされているとみなせなくもないかもしれませんが、これを「握りつぶされる」とだけ記述するのはミスリーディングに思えます。 "誰からも" 隠蔽されるように見えるからです。強いて書くなら ```本シーンを利用している間、すべての `MessageEvent` は、「tick に含められ全プレイヤーに送出される」というデフォルトのイベントハンドリングフローから除外される。ゲーム開発者は必要に応じて `actionReceived` で `MessageEvent` を検出し、 `broadcast()` でそれに相当するメッセージを送出せねばならない ``` というぐらいが実態に即した記述になるのでは。

そして文章上の記述はさておき、もし実態として **ゲーム開発者に対して `MessageEvent` が隠蔽されていないならば、それの順序に関してゲーム開発者に不要な影響を与えるのは避けたい** ように思います。

> 今回の修正では (中略) というごくまれなケースを「例外的に」ケアすることを目的としているため、(中略) の「よほど限定的な条件」に内包されるものなのかと認識しています。
> そういう意味では #25 (comment) にもあるように「コンテンツ制作者からは基本的には使われない」ということを lockConsumingMessageEvent (名前は変更予定ですが) 側にコメントしておくべきですね。

「よほど限定的な条件なら、避けがたければ順序が入れ替わるのを受け入れる余地もある」と述べたつもりです。別に必要がないのに順序を入れ替える理由にはならないと思います。

まあ書かれている通り、非公開機能にしてしまうなら上の影響が現実的に悪い形で出ることは考えにくいかもしれませんが、原則論として、 「関心を持たない」「素通し」とかの方針は透明であるための "手段" であって、 "目的" ではないということは強調しておきたいですね。手段のために目的を損なうべきとは思えません。

2020-11-04 07:55 UTC, yu-ogi commented on packages/coe/src/impl/Scene.ts
> +				}
上記の議論については「`locking` フラグが真である限りすべてのイベントの処理を遅延する = 順序を保証する」としました。これは

> もし実態として ゲーム開発者に対して MessageEvent が隠蔽されていないならば、それの順序に関してゲーム開発者に不要な影響を与えるのは避けたい ように思います。

にあるように「MessageEvent が隠蔽されていない」が現状の coe では不十分であるという理由からです。(詳細は後述します)

---

> 現実には「そのまま tick には載せない代わりに、ゲーム開発者に通知するので、必要なら "ゲーム開発者が改めて送出せよ"」という形ではないでしょうか。握りつぶす＝隠蔽するどころか、ゲーム開発者にはむしろ積極的に露出されています。

念の為の補足ですが、現状の coe は `g.MessageEvent` を意識すべきではないように設計されています。coe は基本的に [Action と Command のデータフロー](https://github.com/akashic-games/coe/blob/master/developers.md) を`g.MessageEvent` の内部的 (隠蔽的) な利用によって実現しているに過ぎず、そのため `g.MessageEvent` を ゲーム開発者が利用することは想定されていません。しかし一ライブラリである coe では `g.MessageEvent` の生成や利用を制限することはできず、上記のケースは coe の内部コードを熟知した例外的なケースに相当するかと思います。

ただ一方で、外部システムによる `g.MessageEvent` の送信における取り扱いについては coe では特に定義されておらず (coe-messages など一部は例外ですが) 、この実装的な都合により、たまたま「外部から送信された `g.MessageEvent` は Action として取り扱われる」という形になっています。このような中途半端な状態が今回な不要な混乱を招いてしまっているように思い、先に述べたような結論といたしました。

2020-11-05 02:38 UTC, xnv approved these changes

2020-11-05 03:15 UTC, merged