Support scenes driven by clock mode
akashic-games/coe pull request #4
Opened 2019-08-30 04:22 UTC by yu-ogi

## このPullRequestが解決する内容
[自動進行モード](https://akashic-games.github.io/reference/akashic-engine-v2/enums/_lib_main_d_.g.tickgenerationmode.html) に対応します。

### 手動進行の場合
* ティックの先頭にタイムスタンプイベントを挿入 (変更なし)
* 1フレームに複数の broadcast data が存在した場合、1つのティックのイベントとして扱うように (変更あり)

### 自動進行の場合
* 自動進行のシーンに変更された際にのみ、最初のティックにタイムスタンプイベントを含ませるように

2019-09-05 14:08 UTC, xnv requested changes

2019-09-05 14:08 UTC, xnv commented on packages/coe/src/impl/Scene.ts
> +			...params
これちゃんと仕様を確認していませんが、プロパティ名が被る時に後勝ちになると思うので

```
{
  local: g.LocalTickMode.InterpolateLocal,
  tickGenerationMode: g.TickGenerationMode.Manual,
  ...params
}
```

これで良かったりしませんか。(というか、後勝ちするので `param.val != null ? (param.val + 1) : 0` みたいに値をそのまま使わない (ここでは `+ 1` している) ケースだとうまく動作しないと思います)

2019-09-05 14:08 UTC, xnv commented on packages/coe/src/impl/Scene.ts
> +			this._sentInitialEvents = false;
これ挙動がうろ覚えなんですけど、 `replaceScene()` とか `popScene()` とかしてきた場合も正しく動作しますかね……？

2019-09-05 14:08 UTC, xnv commented on packages/coe/src/impl/Scene.ts
> +				filtered.unshift([0x2, null, null, Math.floor(g.game.getCurrentTime())]);
`unshift()` だと後続の要素全部コピーしないといけないので、ここの処理 (`!_generateTickManually` のブロック) を真っ先に行うことはできないでしょうか？　概念的にも、すでに  `broadcastDataBuffer` に積まれていたものは、今与えられたイベントよりも先に `filtered` に積まれてよいような気がしますが……。

2019-09-06 01:53 UTC, yu-ogi commented on packages/coe/src/impl/Scene.ts
> +			...params
なるほど、ありがとうございます。修正いたします。

2019-09-06 04:18 UTC, yu-ogi commented on packages/coe/src/impl/Scene.ts
> +				filtered.unshift([0x2, null, null, Math.floor(g.game.getCurrentTime())]);
https://github.com/akashic-games/coe/pull/4/commits/e8f06b4cb6dafdbde903a788c2a89e1203c9b07e
こちら対応しました。

2019-09-06 04:46 UTC, yu-ogi commented on packages/coe/src/impl/Scene.ts
> +			this._sentInitialEvents = false;
以下のミニマムコードを実行してみた限り問題なさそうでした。

```javascript
    var scene1 = new g.Scene({ game: g.game });
    var scene2 = new g.Scene({ game: g.game });
    var scene3 = new g.Scene({ game: g.game });

    scene1.loaded.addOnce(function () {
        console.log("scene1 loaded");
        console.log("=====replace scene2=====");
        g.game.replaceScene(scene2);
    });
    scene1.stateChanged.add(function(state) {
        if (state === g.SceneState.Active) {
            console.log("scene1 actived");
        }
    });

    scene2.loaded.addOnce(function () {
        console.log("scene2 loaded");
        console.log("=====push scene2=====");
        g.game.pushScene(scene3);
    });
    scene2.stateChanged.add(function(state) {
        if (state === g.SceneState.Active) {
            console.log("scene2 actived");
        }
    });

    scene3.loaded.addOnce(function () {
        console.log("scene3 loaded");
        console.log("=====pop scene3=====");
        g.game.popScene();
    });
    scene3.stateChanged.add(function(state) {
        if (state === g.SceneState.Active) {
            console.log("scene3 actived");
        }
    });

    g.game.pushScene(scene1);
```

```
// console
scene1 actived
scene1 loaded
=====replace scene2=====
scene2 actived
scene2 loaded
=====push scene3=====
scene3 actived
scene3 loaded
=====pop scene3=====
scene2 actived
```

2019-09-06 15:41 UTC, xnv commented on packages/coe/src/impl/Scene.ts
> +	private _generateTickManually: boolean = false;
動詞始まりだとメソッド名っぽいので、 `_generates〜` とか  `_isManualTicker` とかはどうでしょう。

2019-09-09 01:34 UTC, yu-ogi commented on packages/coe/src/impl/Scene.ts
> +	private _generateTickManually: boolean = false;
下の `_send~` に合わせて `_generatesTickManually` に直しました。

2019-09-10 03:39 UTC, xnv commented on packages/coe/src/impl/Scene.ts
> +	private raiseTickIfMessageEventExists(): void {
こだわりませんが、長いのでので `IfNeeded` ぐらいでもいいかもしれません。

2019-09-10 03:39 UTC, xnv approved these changes
https://github.com/akashic-games/coe/pull/4/files#r321283518 が特に変更されていないようです。それ以外は大丈夫そうなので approve しました。

2019-09-10 04:38 UTC, yu-ogi commented on packages/coe/src/impl/Scene.ts
> +			...params
別作業で誤って revert してしまっていたみたいです。
95435c7 で差し戻しました。

2019-09-11 04:16 UTC, yu-ogi commented on packages/coe/src/impl/Scene.ts
> +	private raiseTickIfMessageEventExists(): void {
* if needs の条件が現状1つのみ
* private method である

ため、わかりやすさを重視して一旦は名前をこのままにしようと思います。

2019-09-11 04:37 UTC, merged